### ISSUE TITLE
[Widget] Bitbucket

### ISSUE THREAD

**Issue by danielbayerlein** [danielbayerlein/dashboard#1]

**Comment by danielbayerlein** [comment]
See [bitbucket](https://github.com/danielbayerlein/dashboard/tree/bitbucket) branch. /cc @marco-streng

**Comment by chrishelgert** [comment]
it will be his first github pr :)

**Comment by marco-streng** [comment]
yes, i'm a little bit nervous

**Comment by danielbayerlein** [comment]
#18
