### ISSUE TITLE
Time doesnt update

### ISSUE THREAD

**Issue by mortenbirkelund** [danielbayerlein/dashboard#127]
After playing around with this dashboard for some time, I dont understand how the functionality to update the components works. By using the setTimeout() function, the code is only updated 1 time. Is this on purpose. If i replace the setTimeout() with the setInterval() then it works. 

```
 componentDidMount () {
    const { interval } = this.props
    this.timeout = setInterval(() => this.setState({ date: new Date() }), interval)
  }
```

Anybody who can explain to me how the setTimeout should be able of updating the components multiple times?

**Comment by mortenbirkelund** [comment]
The setInterval works, and can be cleared in the componentWillUnmount()

@danielbayerlein If you agree, then let me know and I will create a pull request for it.

**Comment by marco-streng** [comment]
@mortenbirkelund you're welcome to create the PR! 👍🏼

**Comment by danielbayerlein** [comment]
Thank you @mortenbirkelund!
