### ISSUE TITLE
[Widget] Validate necessary information

### ISSUE THREAD

**Issue by chrishelgert** [danielbayerlein/dashboard#16]
it would be good if every widget validates its properties and prints an error message, if the user forget to set a required property (example url for api calls)

**Comment by danielbayerlein** [comment]
I think we should the error state to true. This will show the error icon.

**Comment by chrishelgert** [comment]
development happens in [branch](https://github.com/danielbayerlein/dashboard/tree/validation)

**Comment by danielbayerlein** [comment]
@chrishelgert Which library do you prefer?

**Comment by chrishelgert** [comment]
@danielbayerlein i am unsure if we need really a library to check if the props are filled or not

**Comment by danielbayerlein** [comment]
@chrishelgert Depends whether you want to check whether they are filled or valid.

**Comment by chrishelgert** [comment]
@danielbayerlein this are the most popular ones on npm:

https://www.npmjs.com/package/validator
https://www.npmjs.com/package/joi

maybe i try one of this
