### ISSUE TITLE
sonarqube 504 method not allowed 

### ISSUE THREAD

**Issue by bennychai91** [danielbayerlein/dashboard#86]
I try using sonarqube widget but get http code 504 , because the method has been using is OPTIONS , and sonarqube Is GET. I try to add method: 'GET' , but i get other erorr 401 noAuth

Can u help ?

**Comment by danielbayerlein** [comment]
Hi @bennychai91, do you use your own SonarQube instance? Is an authentication required?

**Comment by bennychai91** [comment]
Yes my SonarQube instance using authentication , and I already add addkey to .env username and password , and i using postman to check the credential and valid , I don't know why ??

    try {
      const res = fetch(`${url}/api/measures/component?componentKey=${componentKey}&metricKeys=${metricKeys}`,
      {
      opts,
      method: 'GET',
      credentials:'same-origin'
      })
      console.log(res)
      const json = await res.json()


<img width="1229" alt="screen shot 2017-12-19 at 12 08 19 pm" src="https://user-images.githubusercontent.com/18244863/34146511-f2a8f89e-e4cc-11e7-8bad-a86ad392a428.png">

**Comment by danielbayerlein** [comment]
Allow your SonarQube instance CORS? See https://github.com/danielbayerlein/dashboard#cross-origin-resource-sharing-cors

**Comment by bennychai91** [comment]
I already using CORS on my local  hapi-rest-proxy , but i get http code 500 internal server errorr ,

My solution right now is not using authentication required , if i using no auth is working well :(

**Comment by danielbayerlein** [comment]
Do you use a self-signed certificate? Please try to start the `hapi-rest-proxy` server with `NODE_TLS_REJECT_UNAUTHORIZED=0`.
